spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tbats
    username: postgres
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true